#! /bin/sh
#
#    ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░
#     ░            ░               ░           ░
#          ░
#

# ----------------------- FUNCTIONS -----------------------

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ----------------------- AUTOSTART -----------------------

# Keybindigs
pgrep -x sxhkd > /dev/null || sxhkd &

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Compositor
picom --config /home/phuong/.config/picom.conf &

# Polybar
~/.config/polybar/launch.sh &

# Notify Daemon
dunst &

# Polkit
[ -n "$(pidof xfce-polkit)" ] || /usr/libexec/xfce-polkit &

# Spotify
[ -n "$(pidof spotify)" ] || spotify &

# Kotatogram
[ -n "$(pidof kotatogram-desktop)" ] || kotatogram-desktop &

# Wallpaper
variety &
fcitx5 &
#~/.fehbg &

thunar --daemon &

# ----------------------- RULES -----------------------

rule Brave-browser         desktop='^2'
rule KotatogramDesktop     desktop='^3'
rule discord               desktop='^6'
rule Transmission-gtk      desktop='^5'
rule Gimp-2.10             desktop='^6'
rule mpv                   desktop='^6' state=fullscreen
rule Leafpad               state=floating
rule Viewnior              state=floating
rule Thunar                state=floating
rule Galculator            state=floating
rule Gucharmap             state=floating
rule Gpick                 state=floating
rule Gcolor2               state=floating
rule Engrampa              state=floating
rule Lxappearance          state=floating

config external_rules_command "$HOME/.config/bspwm/scripts/spotifyrule.sh"

# ----------------------- GENERAL CONFIG -----------------------

bspc monitor -d 1 2 3 4 5 6

config border_width             3
config window_gap               7
config split_ratio              0.50

config borderless_monocle       true
config gapless_monocle          true
bspc config paddingless_monocle true
bspc config single_monocle      false
config focus_follows_pointer    true

config top_padding              48
config bottom_padding           5
config left_padding             5
config right_padding            5

config pointer_modifier         mod4
config pointer_action1          move
config pointer_action2          resize_side
config pointer_action2          resize_corner

config focused_border_color     "#0f0f0f"
config normal_border_color      "#0f0f0f"
config active_border_color      "#4c4c4c"
config borders_width   1

start borders
